#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Create SQL for view_factor_returns_zscore.
- Reads FACTOR_ZSCORE_WINDOW_DAYS from .env (default 252).
- Writes view_factor_returns_zscore.sql.
- This script does NOT execute SQL; run the output in Supabase SQL Editor.
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

DEFAULT_WINDOW_DAYS = 252
VIEW_NAME = "view_factor_returns_zscore"
OUTPUT_PATH = Path("view_factor_returns_zscore.sql")


def read_window_days() -> int:
    raw = os.getenv("FACTOR_ZSCORE_WINDOW_DAYS", "").strip()
    if not raw:
        return DEFAULT_WINDOW_DAYS
    try:
        value = int(raw)
    except ValueError as exc:
        raise RuntimeError("FACTOR_ZSCORE_WINDOW_DAYS must be an integer") from exc
    if value < 2:
        raise RuntimeError("FACTOR_ZSCORE_WINDOW_DAYS must be >= 2")
    return value


def build_sql(window_days: int) -> str:
    window_rows = window_days - 1
    return f"""-- Generated by create_factor_returns_zscore_view.py
-- window_days: {window_days}
CREATE OR REPLACE VIEW public.{VIEW_NAME} AS
WITH base AS (
  SELECT
    r.*,
    avg(r.ret) FILTER (WHERE r.ret <> 0) OVER w AS ret_mean,
    stddev_samp(r.ret) FILTER (WHERE r.ret <> 0) OVER w AS ret_std,
    count(r.ret) FILTER (WHERE r.ret <> 0) OVER w AS ret_n
  FROM public.factor_returns r
  WINDOW w AS (
    PARTITION BY r.factor_code
    ORDER BY r.record_date
    ROWS BETWEEN {window_rows} PRECEDING AND CURRENT ROW
  )
)
SELECT
  base.*,
  CASE
    WHEN base.ret IS NULL THEN NULL
    WHEN base.ret = 0 THEN 0
    WHEN base.ret_std IS NULL OR base.ret_std = 0 THEN 0
    ELSE (base.ret - base.ret_mean) / base.ret_std
  END AS ret_z
FROM base;
"""


def main() -> None:
    load_dotenv(override=False)
    window_days = read_window_days()
    sql = build_sql(window_days)
    OUTPUT_PATH.write_text(sql)
    print(f"[OK] wrote {OUTPUT_PATH} (window_days={window_days})")
    print("Run this SQL in Supabase SQL Editor to apply the view.")


if __name__ == "__main__":
    main()
