-- =========================================================
-- [1. 초기화] 기존 데이터 및 구조 완전 삭제 (Clean Start)
-- =========================================================
DROP VIEW IF EXISTS view_rebalancing_summary CASCADE;
DROP VIEW IF EXISTS view_daily_portfolio_final CASCADE;
DROP VIEW IF EXISTS view_daily_net_worth CASCADE;
DROP VIEW IF EXISTS view_daily_cash_report CASCADE;

DROP TABLE IF EXISTS ticker_category_map CASCADE;
DROP TABLE IF EXISTS manual_cash_flow CASCADE;
DROP TABLE IF EXISTS asset_holdings CASCADE;
DROP TABLE IF EXISTS asset_snapshot CASCADE;

-- =========================================================
-- [2. 테이블 생성]
-- =========================================================

-- 2-1. 매핑 테이블 (asset_type, currency 등 분류 기준)
CREATE TABLE public.ticker_category_map (
    stock_code text primary key,   
    stock_name text,
    asset_type text default '기타', -- (주식, 채권, 현금성자산, 대체투자, 혼합형)
    country text default 'KR',     -- 국가 (KR, US, JP...)
    currency text default 'KRW',   -- 통화 (환헤지 상품은 KRW로 입력)
    tags text,                     -- 태그 (#반도체 #배당)
    description text
);

-- 2-2. 자산 스냅샷 (Master: 일별 계좌 총액)
CREATE TABLE public.asset_snapshot (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    account_no text not null,
    account_name text,
    record_date date not null,
    recorded_at timestamp with time zone,
    total_asset bigint default 0,    
    total_cash bigint default 0,     
    total_stock_amt bigint default 0 
);
ALTER TABLE public.asset_snapshot ADD CONSTRAINT unique_daily_account UNIQUE (account_no, record_date);

-- 2-3. 보유 종목 상세 (Detail: 종목별 잔고)
CREATE TABLE public.asset_holdings (
    id bigint generated by default as identity primary key,
    snapshot_id bigint not null references public.asset_snapshot(id) on delete cascade,
    stock_code text not null,
    stock_name text,
    qty integer default 0,
    buy_price double precision,
    cur_price double precision,
    eval_amt bigint default 0,
    earning_rate double precision
);

-- 2-4. 수동 입출금 내역
CREATE TABLE public.manual_cash_flow (
    id bigint generated by default as identity primary key,
    transaction_date date not null default current_date,
    account_no text not null,
    category text not null,      
    amount bigint not null,      
    memo text
);

-- 2-5. 팩터 수익률 데이터
CREATE TABLE public.factor_returns (
    id bigint generated by default as identity primary key,
    factor_code text not null,
    factor_name text,
    source text,
    source_series text,
    record_date date not null,
    frequency text,
    level double precision,
    ret double precision,
    ret_type text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.factor_returns ADD CONSTRAINT unique_factor_date UNIQUE (factor_code, record_date);

-- =========================================================
-- [3. 뷰(View) 생성]
-- =========================================================

-- 3-1. 통합 포트폴리오 (상세 분석용)
CREATE OR REPLACE VIEW view_daily_portfolio_final AS
WITH daily_grand_total AS (
    SELECT record_date, sum(total_asset) as grand_total_asset 
    FROM asset_snapshot
    GROUP BY record_date
),
unified_assets AS (
    -- [A] 주식/ETF 데이터
    SELECT 
        s.record_date,
        h.stock_code,
        h.stock_name,
        coalesce(m.asset_type, '기타') as asset_type,
        coalesce(m.tags, '#미분류') as tags,
        coalesce(m.country, 'KR') as country,
        coalesce(m.currency, 'KRW') as currency_exposure,
        sum(h.eval_amt) as total_eval_amt,
        sum(h.qty) as total_qty,
        CASE WHEN sum(h.qty) > 0 THEN sum(h.qty * h.buy_price) / sum(h.qty) ELSE 0 END as avg_buy_price,
        avg(h.cur_price) as cur_price,
        CASE WHEN sum(h.qty * h.buy_price) > 0 THEN (sum(h.eval_amt) - sum(h.qty * h.buy_price)) / sum(h.qty * h.buy_price) * 100 ELSE 0 END as earning_rate
    FROM asset_holdings h
    JOIN asset_snapshot s ON h.snapshot_id = s.id
    LEFT JOIN ticker_category_map m ON h.stock_code = m.stock_code
    GROUP BY s.record_date, h.stock_code, h.stock_name, m.asset_type, m.tags, m.country, m.currency

    UNION ALL

    -- [B] 현금 (예수금)
    SELECT 
        record_date,
        'CASH', '예수금',
        '현금성자산',    
        '#현금 #유동성', 
        'KR', 'KRW',     
        sum(total_cash),
        1, 1, 1, 0
    FROM asset_snapshot
    GROUP BY record_date
)
SELECT 
    u.record_date,
    u.asset_type,
    u.tags,
    u.country,
    u.currency_exposure,
    u.stock_name,
    u.stock_code,
    u.total_eval_amt,
    CASE 
        WHEN dt.grand_total_asset > 0 THEN 
            round((u.total_eval_amt::numeric / dt.grand_total_asset) * 100, 2)
        ELSE 0 
    END as weight_percent,
    u.total_qty,
    u.earning_rate
FROM unified_assets u
JOIN daily_grand_total dt ON u.record_date = dt.record_date
ORDER BY u.record_date DESC, u.asset_type, u.total_eval_amt DESC;


-- 3-2. 리밸런싱용 요약 뷰
CREATE OR REPLACE VIEW view_rebalancing_summary AS
WITH daily_total AS (
    SELECT record_date, sum(total_eval_amt) as grand_total
    FROM view_daily_portfolio_final
    GROUP BY record_date
)
SELECT 
    v.record_date,
    v.asset_type,
    sum(v.total_eval_amt) as asset_sum,
    round((sum(v.total_eval_amt)::numeric / max(t.grand_total)) * 100, 2) as weight_percent
FROM view_daily_portfolio_final v
JOIN daily_total t ON v.record_date = t.record_date
GROUP BY v.record_date, v.asset_type
ORDER BY v.record_date DESC, asset_sum DESC;


-- 3-3. 일별 순자산 및 현금흐름 뷰
CREATE OR REPLACE VIEW view_daily_net_worth AS
WITH daily_assets AS (
  SELECT 
    record_date,
    sum(total_asset) as total_asset,
    sum(total_stock_amt) as total_stock_amt,
    sum(total_cash) as total_cash
  from asset_snapshot
  group by record_date
),
daily_flows AS (
  SELECT 
    transaction_date,
    sum(amount) as net_flow_amount
  FROM manual_cash_flow
  GROUP BY transaction_date
)
SELECT 
  a.record_date,
  a.total_asset,      
  a.total_stock_amt,  
  a.total_cash,       
  coalesce(f.net_flow_amount, 0) as daily_cash_flow
FROM daily_assets a
LEFT JOIN daily_flows f ON a.record_date = f.transaction_date
ORDER BY a.record_date DESC;

-- 3-4. 수동 입출금 리포트
CREATE OR REPLACE VIEW view_daily_cash_report AS
SELECT 
    transaction_date, account_no, category,
    count(*) as count,
    sum(amount) as total_amount
FROM manual_cash_flow
GROUP BY transaction_date, account_no, category
ORDER BY transaction_date DESC;

-- [권한 해제] (개인 프로젝트용)
ALTER TABLE asset_snapshot DISABLE ROW LEVEL SECURITY;
ALTER TABLE asset_holdings DISABLE ROW LEVEL SECURITY;
ALTER TABLE manual_cash_flow DISABLE ROW LEVEL SECURITY;
ALTER TABLE ticker_category_map DISABLE ROW LEVEL SECURITY;