-- Run this in your Supabase SQL Editor to fix the factor_returns table structure.

DROP TABLE IF EXISTS public.factor_returns CASCADE;

CREATE TABLE public.factor_returns (
    id bigint generated by default as identity primary key,
    factor_code text not null,
    factor_name text,
    source text,
    source_series text,
    record_date date not null,
    frequency text,
    level double precision,
    ret double precision,
    ret_type text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.factor_returns ADD CONSTRAINT unique_factor_date UNIQUE (factor_code, record_date);

-- Disable RLS for personal project convenience (optional)
ALTER TABLE public.factor_returns DISABLE ROW LEVEL SECURITY;
