-- Run this in your Supabase SQL Editor to fix the factor_returns table structure.

DROP TABLE IF EXISTS public.factor_returns CASCADE;

CREATE TABLE public.factor_returns (
    id bigint generated by default as identity primary key,
    factor_code text not null,
    record_date date not null,
    level double precision,
    ret double precision,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    observed_date date not null,
    effective_kr_date date
);

ALTER TABLE public.factor_returns ADD CONSTRAINT unique_factor_date UNIQUE (factor_code, record_date);

-- factor_metadata (if not exists)
CREATE TABLE IF NOT EXISTS public.factor_metadata (
    factor_code text primary key,
    factor_name text,
    category text,
    description text,
    source text,
    source_series text,
    frequency text,
    ret_type text,
    lag_policy text,
    source_tz text,
    tags text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE OR REPLACE FUNCTION public.set_factor_metadata_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at := timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_factor_metadata_updated_at ON public.factor_metadata;
CREATE TRIGGER trg_factor_metadata_updated_at
BEFORE UPDATE ON public.factor_metadata
FOR EACH ROW EXECUTE FUNCTION public.set_factor_metadata_updated_at();

-- Disable RLS for personal project convenience (optional)
ALTER TABLE public.factor_returns DISABLE ROW LEVEL SECURITY;
