-- Generated by create_factor_returns_zscore_view.py
-- window_days: 252
CREATE OR REPLACE VIEW public.view_factor_returns_zscore AS
WITH base AS (
  SELECT
    r.*,
    avg(r.ret) FILTER (WHERE r.ret <> 0) OVER w AS ret_mean,
    stddev_samp(r.ret) FILTER (WHERE r.ret <> 0) OVER w AS ret_std,
    count(r.ret) FILTER (WHERE r.ret <> 0) OVER w AS ret_n
  FROM public.factor_returns r
  WINDOW w AS (
    PARTITION BY r.factor_code
    ORDER BY r.record_date
    ROWS BETWEEN 251 PRECEDING AND CURRENT ROW
  )
)
SELECT
  base.*,
  CASE
    WHEN base.ret IS NULL THEN NULL
    WHEN base.ret = 0 THEN 0
    WHEN base.ret_std IS NULL OR base.ret_std = 0 THEN 0
    ELSE (base.ret - base.ret_mean) / base.ret_std
  END AS ret_z
FROM base;
